<?php
SESSION_START();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Texas A &amp; M-Kingsville ACM</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" / >
<link rel="stylesheet" type="text/css" href="css/cssreset-min.css" />
<link rel="stylesheet" type="text/css" href="css/style.css" />
<link rel="stylesheet" type="text/css" href="css/main_body.css" />
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/js.js"></script>
<script type="text/javascript" src="js/jquery.stellar.min.js"></script>
<script type="text/javascript" src="js/jquery.waypoints.min.js"></script>
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
</head>

<body>
<!-- Facebook plugin javascript -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<!--Search Bar
 <div id="search_bar" >
 <br />
 <span style="color:#3d4a96;padding-right:0px">Search&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
 <div id="search_bar_hidden">
 <form method="post" action="#" style="height:14px">
 <input size="22.5"style="height:16px;padding-top:2px;" name="search" type="text"/>
 <input style="cursor:pointer;height:19px;width:19px;font-size:small;margin-bottom:1px;background-image:url('images/mag.png')" name="search" type="button"/>
 </form>
 </div>
 <br />
 </div>  

Main Body-->
 <div class="main_body" id="main-body">
<!--Home Slide-->
 <div class="slide" id="slide1" data-slide="1" data-stellar-background-ratio="0"> 
 <div class="screen"></div>
 <br />
 
 
  <div id="homeLogos">
 <img alt=""id="acmLogo" src="images/slide1/ACM_logo.png"/><br />
 <img alt=""id="TowerLogo" src="images/slide1/TowerGold_web.png"/>
 
 </div><br /><br />
 <!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class='csslider1 autoplay ' style="z-index:0;">
		<input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
		<input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
		<ul>
			<li class="cs_skeleton"><img src="images/slide3.jpg" style="width: 100%;"></li>
			<li class='num0 img slide'> <img class="imag" src='images/misc_pics/IMG_20160929_132726.jpg' alt='slide1' title='slide1' /></li>
			<li class='num1 img slide'> <img class="imag" src='images/misc_pics/IMG_20160915_131034.jpg' alt='slide3' title='slide3' /></li>
			<li class='num2 img slide'> <img class="imag"src='images/misc_pics/IMG_20161012_181707.jpg' alt='slide2' title='slide2' /></li>
			
		</ul>
		
		<div class='cs_play_pause'>
			<label class='cs_play' for='cs_play1'><span><i></i><b></b></span></label>
			<label class='cs_pause num0' for='cs_pause1_0'><span><i></i><b></b></span></label>
			<label class='cs_pause num1' for='cs_pause1_1'><span><i></i><b></b></span></label>
			<label class='cs_pause num2' for='cs_pause1_2'><span><i></i><b></b></span></label>
			</div>
		<div class='cs_arrowprev'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_arrownext'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		
		</div>
		<!-- End cssSlider.com --><br /><br />
		
<br /><br />
  <div class="learn_more">
   <br/>
    <a href="http://www.tamuk.edu/" target="_blank"> <span style="color:#3d4a96;">Learn More</span></a>
   <br/>
  </div> 
 <a class="downArrow" data-slide="2" title=""></a>      
 </div>
 
<!--About Slide-->
<a name="about" ></a>
 <div class="slide" id="slide2" data-slide="2" data-stellar-background-ratio="0.0">
 <div class="screen"></div>
    
 <br />
 
	<h4 style="color:white;" >About the ACM Organization</h4>
	 <br /><br /><br /><br /><br /><br /><br />
	 <p class="info">
ACM brings together computing educators, researchers, and professionals to inspire dialogue, share resources, and address the field's challenges. 
As the world’s largest computing society, ACM strengthens the profession's collective voice through strong leadership, promotion of the highest standards, 
and recognition of technical excellence. ACM supports the professional growth of its members by providing opportunities for life‐long learning, career development, 
and professional networking.
</p>
<br/>
<p class="info">
Founded at the dawn of the computer age, ACM’s reach extends to every part of the globe, with more than half of its 100,000 members residing outside the U.S.  
Its growing membership has led to Councils in Europe, India, and China, fostering networking opportunities that strengthen ties within and across countries and 
technical communities.  Their actions enhance ACM’s ability to raise awareness of computing’s important technical, educational, and social issues around the world. 

</p>   
<div class="learn_more">
 <br/>
 <a href="http://www.acm.org/" target="_blank"> <span style="color:#3d4a96;">Learn More</span></a>
 <br/>
 </div>   
 <a class="downArrow" data-slide="3" title=""></a>      
 </div>
 
<!--Member Slide-->
<a name="members" ></a>
 <div class="slide" id="slide3" data-slide="3" data-stellar-background-ratio="0.0">  
 <div class="screen"></div>
 
 <br />
 <h4 style="color:white;">MEMBERS</h4>
 <br />
	<?php
	$myfile = fopen("images/members/member_names.txt", "r") or die("Unable to open file!");
	if(filesize("images/members/member_names.txt")>0){
		$name_string = fread($myfile,filesize("images/members/member_names.txt"));
	}else
	{
		$name_string="";
	}
	fclose($myfile);
	$member_name_arr = explode(",", $name_string);
	for($i=0;$i<count($member_name_arr);$i++)
	{
		$member_name_arr_exp[$i] = explode(" - ", $member_name_arr[$i]);
	}
	//var_dump($member_name_arr_exp);print "<br />";
	$directory = 'images/members/';
	if (glob($directory . '*.jpg') != false)
	{
		$filecount = count(glob($directory . '*.jpg'));
		
	}else
	{
		$filecount=0;
	}
	
	for($i=0;$i<$filecount;$i++)
	{	$f=$i+1;
		for($j=0;$j<count($member_name_arr);$j++)
		{
			if(($f) == $member_name_arr_exp[$j][0]&&file_exists("images/members/$f.jpg"))
			{
				$member_num = $member_name_arr_exp[$j][0];
				$member_name = $member_name_arr_exp[$j][1];
				print "<a class='mem_link' href='members.php?mem=$member_num' style='position:inherit;' ><div style='background-image:url(images/members/$f.jpg)' class='member'><p class='names' >$member_name</p></div></a>";
				
			}
		}
				
	}
	
	?>
 <br />
 <?php
  if(isset($_SESSION['admin'])&&$_SESSION['admin']=="yes")
  {
	  print "<a class='add_members' href='admin.php'>Edit Members<a/>";
	  
  }else
  {
	  print '<a class="add_members" >Edit Members
			 <div class="admin_login">
			 <form class="admin_login_form" action="admin.php" method="POST"><br />
			 <input type="text" size="inherit" name="username" required="required" placeholder="Username" /><br /><br />
			 <input type="password" size="inherit" name="password" required="required" placeholder="Password" /><br /><br />
			 <input type="submit" name="admin_submit" value="Log In" />
			 </form></div></a>';
  }
?>
<br /><br /><br /><br />
 <a class="downArrow" data-slide="4" title=""></a>   
 </div >
 
<!--Project Slide-->
 <div class="slide" id="slide4" data-slide="4" data-stellar-background-ratio="0.0">
<a name="projects" ></a> 
  <div class="screen"></div>
  
 <br />
 <h4 style="color:white;">PROJECTS</h4>
 <br /><br /><br /><br />

     <div  id = "webProject">
     <h4>The TAMUK-ACM Announces Entry into the Outstanding Chapter Website Competition</h4>
     <br />
     <br />
     <p ><img src="images/placeholder.jpg" alt ="placeholder" id = "webPhoto" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dapibus vel sem nec bibendum. Donec sit ametdolor convallis,
         interdum elit sed, maximus mi. Suspendisse nec lectus dolor. Quisque eget ante nec leo cursus scelerisque.Nulla facilisis
         justo felis, sed efficitur sem malesuada id. Proin ac maximus lacus, eget mollis leo. Pellentesque facilisis magnaquis nunc
         ultricies euismod. Duis placerat, leo sit amet finibus varius, nisl tellus placerat augue, ac dignissim erat ante vitae lorem.
         Nulla in ipsum consequat, pellentesque tortor eget, placerat purus. Donec elit neque, posuere in libero a, finibus eleifend urna.
         In non dolor vitae nunc tempus consequat. Sed nec nisl est. Sed egestas, lectus vitae imperdiet varius, ipsum dolor dignissim ex,
     </p><br/>

     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dapibus vel sem nec bibendum. Donec sit ametdolor convallis,
         interdum elit sed, maximus mi. Suspendisse nec lectus dolor. Quisque eget ante nec leo cursus scelerisque.Nulla facilisis
         justo felis, sed efficitur sem malesuada id. Proin ac maximus lacus, eget mollis leo. Pellentesque facilisis magnaquis nunc
         ultricies euismod. Duis placerat, leo sit amet finibus varius, nisl tellus placerat augue, ac dignissim erat ante vitae lorem.
         Nulla in ipsum consequat, pellentesque tortor eget, placerat purus. Donec elit neque, posuere in libero a, finibus eleifend urna.
         In non dolor vitae nunc tempus consequat. Sed nec nisl est. Sed egestas, lectus vitae imperdiet varius, ipsum dolor dignissim ex,
     </p><br/>

     <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dapibus vel sem nec bibendum. Donec sit ametdolor convallis,
         interdum elit sed, maximus mi. Suspendisse nec lectus dolor. Quisque eget ante nec leo cursus scelerisque.Nulla facilisis
         justo felis, sed efficitur sem malesuada id. Proin ac maximus lacus, eget mollis leo. Pellentesque facilisis magnaquis nunc
         ultricies euismod. Duis placerat, leo sit amet finibus varius, nisl tellus placerat augue, ac dignissim erat ante vitae lorem.
         Nulla in ipsum consequat, pellentesque tortor eget, placerat purus. Donec elit neque, posuere in libero a, finibus eleifend urna.
         In non dolor vitae nunc tempus consequat. Sed nec nisl est. Sed egestas, lectus vitae imperdiet varius, ipsum dolor dignissim ex,
     </p><br/>

    

     </div>
	 <hr>
	 <div  id = "webProject">
    <h4>TAMUK-ACM's Inaugural Undertaking of the International Collegiate Programming Competition</h4>
    <br />
    <br />
    <p ><a href="https://icpc.baylor.edu/" target="_ blank"><img src="images/acmicpc_logo.png" alt ="placeholder" id = "webPhoto" /></a>As most students were mentally preparing for an upcoming break in the Fall of 2016, a few members of the Texas A&M-Kingsville (TAMUK) chapter of the Association for Computing Machinery (ACM) were preparing to compete in their very first ACM International Collegiate Programming Competition (ICPC).
	</p>
	<p > 
	Held every school year, the ACM-ICPC is an international competition sponsored by IBM where schools from all across the world meet to see who is the best at programming in the Java, PHP, C, C++, and Python coding languages.  The competition is so large and widespread, that it is held, concurrently, in many schools over several continents.  Each participating country is then broken up into several regions.  TAMUK is in the south-central region of the U.S. and the main regional competition was held at Baylor University in Waco, Texas.  The winners of these regional competitions then go on to meet at a final competition.  The location of the 2016 final competition was the Prince of Sangkla University in Phuket, Thailand.</p>
	<p >
	Here's a brief rundown of what happens at a programming competition.  After all the initial signing in and receiving of instructions and such, the various teams are given a packet of information containing eight real-world problems.  They are also given a look at what the correct output should look like (output is not the program itself, it is the data that is provided by a program).  These teams then have five hours to determine how to best address these problems and create programs that give the correct output using all the programming knowledge and experience they can muster.  All answers are then scored based on the accuracy of the output and the speed at which the problem was solved.</p>
	</br>
	<div class="quote">"Solving these problems helped me gain a better understanding of the language."<small>-Tyler Hurson</small></div>
	</br>
	<p >
	The two teams consisted of: Tyler Hurson, Hayden Judson, Nikolas Walker, Oscar Reyes, Bradley Guerrero, Samantha Villanueva, Emily Saenz, Stephanie Garza, and Jude Alonge.  The teams would also like to extend a special thank you to Dr. David Hicks and the entire <a style="text-decoration:underline;" class="projects_link" href="http://www.tamuk.edu/engineering/" target="_blank">Frank H. Dotterweich College of Engineering</a> for their sponsorship, and Thomas Wurdinger for his help. This was the TAMUK-ACM's very first attendance of such an event and while the teams will not be competing in the finals this year, many great lessons were learned and brought back to the TAMUK-ACM to be passed on to next year's competitors.  When asked to give us his account, coach Tyler Hurson had this to say:</p>
	<p>"It was a very fun experience. Overall, everyone had a great time and I am very proud of both teams. The only boring part was the five hour car ride!  Solving these problems helped me gain a better understanding of the language(s). In addition, our experience this time around has given me some insight on how we can develop a more competitive team next year."</p>
	<iframe width="280" height="157.5" src="https://www.youtube.com/embed/3rfZpKe9rdg" frameborder="0" allowfullscreen></iframe>
     </div>
	 </br></br></br></br>
 <a class="downArrow" data-slide="5" title=""></a>

 </div>


 
<!--Join Now Slide-->
 <div class="slide" id="slide5" data-slide="5" data-stellar-background-ratio="0.0"> 
 <a name="join_us" ></a>
 <div class="screen"></div>

 <br />
 <h4 style="color:white;">JOIN NOW</h4>
 <br /><br /><br /><br /><br /><br /><br /><br />
 <p class="info">
 If you would like more information about joining the Texas A &amp; M Kingsville
 chapter of ACM please email pgarcia@thomaswurdinger.com
 </p>
 <br/>
 <p class="info">
 The 'Learn More' tab at the upper right corner will take you to the ACM membership page
 where you can find additional sign up information and forms.
 </p>
 
<div class="learn_more">
 <br/>
 <a href="http://www.acm.org/membership/join-acm" target="_blank"> <span style="color:#3d4a96;">Learn More</span></a>
 <br/>
 </div> 
<!--Button Overlays-->
 </div>
 <!--Beginning of Side Bar-->
 <div id="side-bar">
<!--Home-->
 <a href="#" class="buttons" data-slide="1" title="">   
 <span><img src="images/house.png" alt=""/></span><span>Home</span>
 </a>
<!--About-->
 <a href="#" class="buttons" data-slide="2" title="">
 <span><img src="images/About.png" alt=""/></span><span>About</span>
 </a>
<!--Members-->
 <a href="#" class="buttons" data-slide="3" title="">
 <span><img src="images/Members.png" alt=""/></span><span>Members</span>
 </a>
<!--Projects-->
 <a href="#" class="buttons" data-slide="4" title=""> 
 <span><img src="images/Projects.png" alt=""/></span><span>Projects</span>
 </a>
<!--Join Now-->
  <a href="#" class="buttons" data-slide="5" title=""> 
  <span><img src="images/JoinNow.png" alt=""/></span><span>Join Now</span>
  </a> 
<!--Follow Us-->
  <a class="buttons" title=""><span id="FU"data-slide="6" title="">
  <b>Follow Us</b></span></a>
  <!--Youtube-->
  <a href="https://www.youtube.com/channel/UCY9beuTTuzTVdlTDZ8lITOg" target="_blank" class="buttons" > 
  <span><img src="images/Youtube.png" alt=""/></span><span>Youtube</span>
  </a>
<!--Twitter-->
<div id="twitterFeed" style="width:100%;">
  <a href="https://twitter.com/ACM_TAMUK" class="buttons" style="height:100%" data-slide="8" title=""> 
  <span><img src="images/Twitter.png" alt=""/></span><span>Twitter</span>
  </a> <div class="twitter-timeline">
  <a class="twitter-timeline" data-width="265" data-height="400"  href="https://twitter.com/ACM_TAMUK">Tweets by ACM_TAMUK</a> 
 
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8" ></script>
  </div>
  </div>
<!--Facebook-->
<div id="facebookFeed" style="width:100%;">
  <a href="https://www.facebook.com/acmtamuk" target="_blank" style="height:100%" class="buttons" data-slide="9" title="">
  <span><img src="images/facebook.png" alt=""/></span><span>Facebook</span>
  </a>
  <div class="fb-page" data-href="https://www.facebook.com/acmtamuk" data-tabs="timeline" data-width="270px" data-height="400" data-small-header="true" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="false">
  <blockquote cite="https://www.facebook.com/acmtamuk" class="fb-xfbml-parse-ignore">
  <a href="https://www.facebook.com/acmtamuk">TAMUK-ACM</a></blockquote>
  </div></div>
 <!--Empty Space-->
  <div class="buttons" data-slide="10" title=""> 
  &nbsp;
  </div>
  </div>

 </div>
<div class="side_bar_overlay" >
<a href="#" class="buttony" data-slide="1" title=""><img class="imgButton" src="images/house.png" alt=""/>
<div class="popout1" >
Home
</div>
</a>
<a href="#" class="buttony" data-slide="2" title=""><img class="imgButton" src="images/About.png"  alt=""/>
<div class="popout2" >
About Us
</div></a>
<a href="#" class="buttony" data-slide="3" title=""><img class="imgButton" src="images/Members.png" alt=""/>
<div class="popout3" >
Members
</div></a>
<a href="#" class="buttony" data-slide="4" title=""><img class="imgButton" src="images/Projects.png" alt=""/>
<div class="popout4" >
Projects
</div></a>
<a href="#" class="buttony" data-slide="5" title=""><img  class="imgButton" src="images/JoinNow.png" alt=""/>
<div class="popout5" >
Join Now
</div>
</a>
<img id="FUsmall" src="images/FU.png" alt=""/>
<a href="https://www.youtube.com/channel/UCY9beuTTuzTVdlTDZ8lITOg" target="_blank" class="buttony" data-slide="9" title=""><img class="imgButton" src="images/Youtube.png" alt=""/></a>
<div id="twitterFeed" style="width:100%;">
  <a href="#" class="buttony" data-slide="7" title="" style="height:100%;" ><img class="imgButton" src="images/Twitter.png" alt=""/></a> 
 
  </a> <div class="twitter-timeline">
  <a class="twitter-timeline" data-width="265" data-height="400"  href="https://twitter.com/ACM_TAMUK">Tweets by ACM_TAMUK</a> 
 
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8" ></script>
  </div>
  </div>


<div id="facebookFeed" style="height:10%">
<a href="#" style="height:100%" class="buttony" data-slide="8" title="" ><img class="imgButton" src="images/facebook.png" alt=""/></a>
<div class="fb-page" data-href="https://www.facebook.com/acmtamuk" data-tabs="timeline" data-width="270px" data-height="400" data-small-header="true" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="false">

  <blockquote cite="https://www.facebook.com/acmtamuk" class="fb-xfbml-parse-ignore">
  <a href="https://www.facebook.com/acmtamuk">TAMUK-ACM</a></blockquote>
  </div>
  </div>
<div class="buttony" data-slide="9" title=""><img class="imgButton" src="images/Blank.png" alt=""/></div>
</div>
<div class="copyright" >&copy; 2016 | Texas A &amp; M University-Kingsville Association for Computing Machinery</div>
 
 </body>
 </html>
